--1)
--1.1)

--drop in this order to avoid conflicts
DROP TABLE ZH_PRODUCT;
DROP SEQUENCE SQ_ZH_PRODUCT;
DROP TABLE ZH_USER;

CREATE TABLE ZH_USER (
    USERNAME VARCHAR2(40) PRIMARY KEY NOT NULL,
    PASSWORD VARCHAR2(40) NOT NULL,
    EMAIL VARCHAR2(40) NOT NULL UNIQUE,
    REGISTRATION DATE NOT NULL
);

CREATE TABLE ZH_PRODUCT (
    ID NUMBER(9, 0) PRIMARY KEY NOT NULL,
    NAME VARCHAR2(40) NOT NULL,
    QUANTITY NUMBER(9, 0) NOT NULL,
    PRICE NUMBER(24,4) NOT NULL,
    ANNOUNCEMENT DATE NOT NULL,
    SELLER VARCHAR2(40) NOT NULL REFERENCES ZH_USER,
    BUYER VARCHAR2(40) REFERENCES ZH_USER
);

CREATE SEQUENCE SQ_ZH_PRODUCT START WITH 1;
-- run the set define off together with the trigger statement
SET DEFINE OFF;
CREATE OR REPLACE TRIGGER BI_TRG_ZH_PRODUCT 
BEFORE INSERT ON ZH_PRODUCT 
FOR EACH ROW
BEGIN
  SELECT SQ_ZH_PRODUCT.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

--1.2)
INSERT INTO ZH_USER (USERNAME, PASSWORD, EMAIL, REGISTRATION) VALUES ('A', 'A', 'A@A.A', SYSDATE);
INSERT INTO ZH_USER (USERNAME, PASSWORD, EMAIL, REGISTRATION) VALUES ('B', 'B', 'B@B.B', SYSDATE);

INSERT INTO ZH_PRODUCT(NAME, QUANTITY, PRICE, ANNOUNCEMENT, SELLER) VALUES('Ha', 1, 10, SYSDATE, 'A');
INSERT INTO ZH_PRODUCT(NAME, QUANTITY, PRICE, ANNOUNCEMENT, SELLER) VALUES('Hb', 1, 10, SYSDATE, 'B');

--1.3)
UPDATE ZH_PRODUCT SET BUYER = 'A' WHERE NAME = 'Hb' AND SELLER = 'B';
--1.4)
--DELETE FROM ZH_PRODUCT WHERE ID = 1;
DELETE FROM ZH_PRODUCT WHERE NAME = 'Ha' AND SELLER = 'A';

--2)
SELECT DNEV, LENGTH(DNEV) AS NEV_LENGHT--, FOGLALKOZAS 
FROM DOLGOZO 
WHERE SUBSTR(FOGLALKOZAS,1,1) = 'C' OR SUBSTR(FOGLALKOZAS,1,1) = 'M'
ORDER BY FOGLALKOZAS;

--3
SELECT

