SELECT DOLGOZO.DNEV AS "Dolgozó Név", DOLGOZO.FIZETES AS "Dolgozó Fizetés", FIZFOKOZAT.KATEGORIA AS "Fizetési Kategória"
FROM DOLGOZO
JOIN FIZFOKOZAT ON DOLGOZO.FIZETES >= FIZFOKOZAT.ALSO AND DOLGOZO.FIZETES <= FIZFOKOZAT.FELSO;
